networks:
  otlp:

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
    environment:
      - COLLECOTR_ZIPKIN_HOST_PORT=:9411
    networks:
      - otlp
  otel:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4318:4318"   # OTLP HTTP
      - "4317:4317"
    networks:
      - otlp
  kong:
    image: kong/kong-gateway:3.10.0.1
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
    volumes:
      - ./kong:/kong/declarative
    networks:
      - otlp
  python:
    build: python
    environment:
      - OTEL_COLLECTOR_URL=otel
    # expose:
    #   - 5000
    ports:
      - 5000:5000
    networks:
      - otlp
  node:
    build: node
    environment:
      - PYTHON_URL=http://python:5000
      - OTEL_COLLECTOR_URL=otel
    # expose:
    #   - 3000
    ports:
      - 3000:3000
    networks:
      - otlp
